In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
reg = linear_model.LinearRegression()

In [13]:
df=pd.read_csv('Add_sales_data_2018.csv')
df
df=df.drop(['Date'], axis=1)
df

,Add1(in Thousands),Add2(in Thousands),Add3(in Thousands),Add4(in Thousands),Add5(in Thousands),Profit(in Thousands)
0,208.00,222.25,206.85,216.00,215.15,4093.065
1,217.00,218.60,205.90,210.25,209.20,4042.448
2,223.50,227.80,216.15,217.25,218.20,4213.819
3,230.00,237.50,225.75,226.45,227.60,4391.665
4,234.55,234.60,221.05,230.30,230.90,4350.683
...,...,...,...,...,...,...
200,288.00,288.25,279.20,284.50,284.30,5374.105
201,290.00,292.50,282.20,284.80,284.45,5439.655
202,298.60,298.60,286.65,287.45,287.80,5545.013
203,290.00,299.55,285.90,297.85,298.35,5565.444
204,287.55,289.90,285.05,288.05,288.45,5421.842

In [12]:
arr = df.to_numpy()
arr

array([[ 208.   ,  222.25 ,  206.85 ,  216.   ,  215.15 , 4093.065],
       [ 217.   ,  218.6  ,  205.9  ,  210.25 ,  209.2  , 4042.448],
       [ 223.5  ,  227.8  ,  216.15 ,  217.25 ,  218.2  , 4213.819],
       ...,
       [ 298.6  ,  298.6  ,  286.65 ,  287.45 ,  287.8  , 5545.013],
       [ 290.   ,  299.55 ,  285.9  ,  297.85 ,  298.35 , 5565.444],
       [ 287.55 ,  289.9  ,  285.05 ,  288.05 ,  288.45 , 5421.842]])

In [5]:
from sklearn.model_selection import train_test_split

In [33]:
X=arr[:,0:5]
X
Y=arr[:,5]
X

array([[208.  , 222.25, 206.85, 216.  , 215.15],
       [217.  , 218.6 , 205.9 , 210.25, 209.2 ],
       [223.5 , 227.8 , 216.15, 217.25, 218.2 ],
       ...,
       [298.6 , 298.6 , 286.65, 287.45, 287.8 ],
       [290.  , 299.55, 285.9 , 297.85, 298.35],
       [287.55, 289.9 , 285.05, 288.05, 288.45]])

In [34]:
df.corr()

,Add1(in Thousands),Add2(in Thousands),Add3(in Thousands),Add4(in Thousands),Add5(in Thousands),Profit(in Thousands)
Add1(in Thousands),1.000000,0.990976,0.986274,0.976365,0.976716,0.991975
Add2(in Thousands),0.990976,1.000000,0.987990,0.989921,0.990285,0.999145
Add3(in Thousands),0.986274,0.987990,1.000000,0.991343,0.991908,0.993389
Add4(in Thousands),0.976365,0.989921,0.991343,1.000000,0.999699,0.993346
Add5(in Thousands),0.976716,0.990285,0.991908,0.999699,1.000000,0.993710
Profit(in Thousands),0.991975,0.999145,0.993389,0.993346,0.993710,1.000000

In [35]:
x_train, x_test, y_train, y_test = train_test_split(X,Y)

In [36]:
x_train

array([[265.95, 269.9 , 261.1 , 262.9 , 262.15],
       [302.9 , 303.7 , 286.1 , 291.15, 290.65],
       [246.5 , 252.35, 245.55, 250.  , 250.2 ],
       [274.65, 274.65, 266.05, 267.  , 267.05],
       [265.  , 268.85, 262.2 , 266.5 , 266.6 ],
       [235.  , 238.5 , 235.  , 237.4 , 237.55],
       [252.2 , 259.4 , 252.2 , 258.5 , 257.85],
       [271.55, 276.85, 269.15, 274.9 , 275.35],
       [223.45, 236.7 , 223.3 , 234.  , 233.95],
       [240.  , 240.  , 232.5 , 235.  , 234.25],
       [271.  , 273.1 , 263.25, 264.5 , 264.45],
       [263.  , 268.25, 261.45, 265.05, 263.95],
       [251.05, 258.9 , 250.  , 258.2 , 257.9 ],
       [301.  , 306.35, 299.7 , 302.8 , 302.75],
       [268.7 , 274.2 , 261.65, 263.  , 262.85],
       [262.75, 266.7 , 260.35, 265.55, 265.75],
       [275.  , 281.65, 273.  , 276.75, 277.8 ],
       [248.4 , 249.6 , 232.7 , 238.1 , 238.65],
       [236.05, 242.  , 235.95, 240.35, 239.35],
       [273.9 , 277.8 , 271.65, 273.9 , 273.85],
       [237.9 , 239.25, 233.5 , 235.5 , 235.05],
       [233.85, 237.7 , 232.7 , 234.2 , 234.55],
       [284.35, 285.25, 276.  , 279.85, 279.05],
       [300.95, 307.3 , 299.45, 304.  , 304.  ],
       [259.7 , 263.65, 255.1 , 263.3 , 262.05],
       [264.2 , 271.9 , 263.  , 271.2 , 270.7 ],
       [280.25, 282.75, 274.2 , 275.5 , 275.6 ],
       [223.5 , 227.8 , 216.15, 217.25, 218.2 ],
       [234.05, 235.95, 230.2 , 233.5 , 233.75],
       [232.5 , 238.05, 230.4 , 235.  , 235.45],
       [244.1 , 248.35, 240.55, 244.  , 243.55],
       [301.  , 303.8 , 297.75, 302.  , 300.85],
       [272.6 , 273.  , 258.35, 260.65, 260.6 ],
       [235.15, 240.45, 234.15, 240.  , 239.5 ],
       [240.8 , 244.5 , 239.2 , 242.7 , 243.  ],
       [237.3 , 237.95, 231.1 , 233.65, 233.55],
       [222.5 , 235.15, 220.65, 221.05, 222.  ],
       [315.05, 328.35, 315.  , 325.95, 325.75],
       [243.4 , 249.65, 241.5 , 247.1 , 246.9 ],
       [264.8 , 269.7 , 263.3 , 264.6 , 267.35],
       [267.  , 270.5 , 265.35, 270.  , 269.6 ],
       [286.  , 288.65, 283.6 , 285.55, 286.2 ],
       [273.55, 274.8 , 271.55, 274.8 , 273.5 ],
       [292.5 , 293.65, 288.75, 291.2 , 291.2 ],
       [241.  , 243.95, 239.15, 242.5 , 242.25],
       [290.25, 294.9 , 278.6 , 289.55, 288.35],
       [216.35, 223.7 , 212.65, 221.65, 222.65],
       [262.7 , 270.15, 262.7 , 269.2 , 269.35],
       [283.  , 288.  , 281.8 , 283.7 , 283.15],
       [274.8 , 275.45, 267.45, 270.  , 269.8 ],
       [290.  , 292.5 , 282.2 , 284.8 , 284.45],
       [289.6 , 294.35, 288.6 , 292.  , 292.  ],
       [293.45, 294.4 , 291.05, 291.4 , 292.1 ],
       [275.9 , 277.8 , 272.55, 274.55, 274.75],
       [258.05, 262.35, 255.5 , 258.15, 258.2 ],
       [243.7 , 247.  , 240.9 , 243.65, 242.2 ],
       [277.  , 277.05, 263.  , 269.  , 267.95],
       [282.  , 286.5 , 276.1 , 280.4 , 280.45],
       [306.5 , 309.3 , 303.55, 306.8 , 306.6 ],
       [274.55, 277.  , 271.5 , 273.  , 273.  ],
       [236.  , 239.  , 232.  , 235.2 , 234.65],
       [267.  , 272.  , 260.7 , 269.05, 269.2 ],
       [278.05, 281.3 , 273.2 , 278.2 , 278.2 ],
       [263.7 , 264.75, 257.  , 260.55, 260.85],
       [277.45, 282.4 , 270.  , 271.8 , 271.25],
       [280.2 , 280.7 , 274.1 , 275.8 , 275.5 ],
       [292.75, 292.75, 283.1 , 286.45, 286.65],
       [262.75, 268.4 , 262.75, 267.2 , 267.6 ],
       [254.7 , 262.2 , 254.65, 260.7 , 260.65],
       [265.1 , 276.9 , 255.15, 275.5 , 273.1 ],
       [308.05, 318.  , 306.35, 316.05, 316.4 ],
       [265.  , 265.75, 257.55, 258.3 , 258.9 ],
       [257.4 , 262.7 , 257.  , 257.9 , 257.5 ],
       [231.25, 240.95, 231.25, 238.9 , 238.6 ],
       [257.9 , 257.9 , 242.1 , 243.9 , 243.25],
       [288.8 , 295.5 , 287.  , 295.05, 294.2 ],
       [304.  , 311.25, 301.65, 305.3 , 304.25],
       [270.5 , 274.2 , 265.  , 273.15, 273.4 ],
       [264.5 , 284.5 , 262.7 , 280.1 , 281.  ],
       [296.  , 296.2 , 287.25, 289.5 , 289.7 ],
       [258.05, 263.5 , 253.7 , 263.45, 262.2 ],
       [274.  , 280.2 , 272.55, 279.4 , 279.65],
       [234.55, 234.6 , 221.05, 230.3 , 230.9 ],
       [224.  , 225.  , 218.2 , 220.95, 221.05],
       [259.35, 278.4 , 259.35, 277.45, 276.95],
       [317.6 , 319.65, 314.  , 314.7 , 315.3 ],
       [240.3 , 240.6 , 233.1 , 235.5 , 235.45],
       [265.3 , 266.3 , 262.15, 262.9 , 263.2 ],
       [264.65, 264.65, 257.6 , 259.1 , 258.85],
       [259.  , 270.3 , 253.25, 266.  , 266.7 ],
       [289.  , 289.95, 286.15, 287.1 , 286.85],
       [305.5 , 308.8 , 302.5 , 305.65, 305.55],
       [276.7 , 283.1 , 271.45, 272.5 , 274.15],
       [284.4 , 290.5 , 284.4 , 287.  , 287.5 ],
       [290.  , 299.55, 285.9 , 297.85, 298.35],
       [275.  , 279.7 , 273.1 , 275.4 , 275.  ],
       [283.05, 291.25, 282.05, 289.1 , 289.1 ],
       [323.  , 326.9 , 311.45, 317.6 , 316.4 ],
       [275.  , 277.35, 274.1 , 275.45, 274.85],
       [275.9 , 275.9 , 266.6 , 268.5 , 268.35],
       [235.35, 237.3 , 232.1 , 237.3 , 236.  ],
       [311.9 , 315.15, 310.15, 310.95, 311.2 ],
       [278.  , 284.4 , 277.25, 279.55, 279.6 ],
       [240.  , 245.6 , 237.25, 241.4 , 241.1 ],
       [237.  , 239.3 , 231.3 , 232.9 , 233.35],
       [257.9 , 263.55, 256.45, 261.95, 262.1 ],
       [327.7 , 328.75, 321.65, 323.7 , 323.  ],
       [315.  , 319.1 , 312.55, 314.25, 314.1 ],
       [282.  , 285.25, 277.5 , 280.6 , 280.95],
       [273.  , 277.  , 272.  , 275.4 , 275.5 ],
       [306.  , 310.7 , 302.8 , 303.7 , 304.25],
       [251.  , 255.5 , 247.3 , 255.  , 254.5 ],
       [313.85, 317.  , 307.55, 314.05, 313.55],
       [235.9 , 242.95, 234.5 , 239.5 , 239.1 ],
       [282.3 , 287.45, 279.25, 285.35, 284.1 ],
       [281.  , 281.  , 275.35, 277.7 , 277.3 ],
       [208.  , 222.25, 206.85, 216.  , 215.15],
       [312.  , 313.5 , 307.25, 312.3 , 312.25],
       [275.25, 281.25, 275.25, 279.  , 278.5 ],
       [233.  , 236.45, 232.25, 235.2 , 234.55],
       [248.3 , 248.95, 243.35, 245.1 , 244.7 ],
       [236.65, 239.85, 235.3 , 237.25, 237.3 ],
       [234.55, 236.8 , 231.1 , 233.8 , 233.25],
       [269.8 , 278.75, 268.2 , 278.  , 277.8 ],
       [222.5 , 225.4 , 214.85, 216.35, 216.  ],
       [234.5 , 237.2 , 230.2 , 231.5 , 231.  ],
       [244.  , 251.1 , 244.  , 247.6 , 247.15],
       [233.3 , 236.75, 232.  , 236.25, 236.1 ],
       [314.3 , 314.95, 307.55, 310.7 , 311.15],
       [298.6 , 298.6 , 286.65, 287.45, 287.8 ],
       [246.9 , 246.9 , 239.25, 240.9 , 240.55],
       [241.  , 241.55, 235.3 , 237.5 , 237.6 ],
       [314.  , 316.7 , 311.8 , 313.1 , 313.3 ],
       [237.25, 240.5 , 235.05, 236.35, 236.35],
       [248.7 , 254.95, 234.35, 235.1 , 235.65],
       [287.05, 291.5 , 282.3 , 287.9 , 287.8 ],
       [314.65, 319.2 , 312.2 , 317.45, 317.6 ],
       [274.  , 277.35, 271.75, 275.7 , 275.5 ],
       [270.  , 276.65, 269.7 , 276.  , 276.05],
       [280.  , 293.95, 275.1 , 291.6 , 290.85],
       [269.8 , 273.25, 265.7 , 266.2 , 266.3 ],
       [312.3 , 315.85, 310.35, 312.85, 312.95],
       [282.4 , 289.6 , 279.7 , 284.25, 285.1 ],
       [302.25, 303.  , 298.15, 300.2 , 300.15],
       [280.8 , 282.7 , 271.05, 272.55, 272.4 ],
       [235.  , 237.  , 227.95, 233.75, 234.6 ],
       [287.55, 289.9 , 285.05, 288.05, 288.45],
       [261.25, 264.  , 257.5 , 259.15, 258.75],
       [280.  , 281.35, 251.85, 257.  , 255.9 ],
       [306.  , 310.  , 300.95, 309.9 , 308.35],
       [233.55, 239.2 , 230.75, 234.  , 233.3 ],
       [233.15, 238.  , 230.25, 236.4 , 236.6 ],
       [221.  , 224.5 , 219.1 , 223.15, 222.95]])

In [37]:
reg.fit(x_train,y_train)

LinearRegression()

In [38]:
reg.coef_

array([ 1.  , 12.38,  3.5 ,  1.  ,  0.9 ])

In [39]:
reg.predict([[290,321,309,298,320]])

array([5931.48])